import { WarningModel } from './WarningModel';
import { ModuleStateCategory, WarningCategory } from "./utils";


// class DefaultMessages {
//     static core(details?) {
//         let message = "{} has been integrated into core Foundry, so it should be uninstalled.";
//         if(details) {
//             message += " " + details;
//         }
//         return message;
//     }

//     static broken() {
//         let message = "{} is partially broken and is no longer being maintained. As it could break further with any Foundry update, it is recommended that you uninstall it.";
//         return message;
//     }

//     static replaced(replacement) {
//         let message = "{} is no longer being maintained and could break with any Foundry update, if it hasn't already. It is recommended that you replace it with ";
//         message += "<b><u>" + replacement + "</u></b>.";
//         return message;
//     }

//     static delisted() {
//         let message = "{} has been removed from Foundry's official module repository because it is no longer being maintained."
//         message += "You should consider uninstalling it, and it could break with any Foundry update."
//         return message
//     }
// }

/**
 * Each warning has the following possible fields:
 * id: Used to remember which warnings the user has ignored.
 * module: The name of the deprecated module.
 * category: Why the module is deprecated.
 * message: The message to be shown to the user.
 * coreVersion: The version the module was deprecated (either integrated into core or broken). If Foundry's version is lower than this, the warning won't be shown.
 * highestVersion: (Optional) If the module's version is higher than this, no warning will be shown.
 * inactive: (Optional) If true, this warning won't be shown to the user.
 */
export const warnings:WarningModel[] = [
    //Core Warnings (0-199)
    {
        id: 0,
        module: "deselection",
        moduleTitle: "Deselection",
        category: WarningCategory.Core,
        message: "To enable it in Foundry, go to 'Configure Settings' -> 'Core Settings' and check 'Left-Click to Release Objects'.",
        coreVersion: "0.7.5",
        urlFoundryHub: "",
        moduleSuggested: [],
        moduleSuggestedTitle: [],
        moduleSuggestedUrl: [],
        moduleSuggestedManifestJson: [],
        moduleSuggestedState: []
    },
    {
        id: 1,
        module: "quicksceneview",
        moduleTitle: "Quick Scene View",
        category: WarningCategory.Core,
        message: "",
        coreVersion: "0.7.5",
        urlFoundryHub: "",
        moduleSuggested: [],
        moduleSuggestedTitle: [],
        moduleSuggestedUrl: [],
        moduleSuggestedManifestJson: [],
        moduleSuggestedState: []
    },
    {
        id: 2,
        module: "BatchPermissionsByFolder",
        moduleTitle: "Batch Permissions By folder",
        category: WarningCategory.Core,
        message: "",
        coreVersion: "0.7.5",
        urlFoundryHub: "",
        moduleSuggested: [],
        moduleSuggestedTitle: [],
        moduleSuggestedUrl: [],
        moduleSuggestedManifestJson: [],
        moduleSuggestedState: []
    },
    {
        id: 3,
        module: "note-text-color",
        moduleTitle: "Note Text Color",
        category: WarningCategory.Core,
        message: "",
        coreVersion: "0.7.5",
        urlFoundryHub: "",
        moduleSuggested: [],
        moduleSuggestedTitle: [],
        moduleSuggestedUrl: [],
        moduleSuggestedManifestJson: [],
        moduleSuggestedState: []
    },
    {
        id: 4,
        module: "no-summon-vision",
        moduleTitle: "No summon vision",
        category: WarningCategory.Core,
        message: "",
        coreVersion: "0.7.5",
        urlFoundryHub: "",
        moduleSuggested: [],
        moduleSuggestedTitle: [],
        moduleSuggestedUrl: [],
        moduleSuggestedManifestJson: [],
        moduleSuggestedState: []
    },
    {
        id: 5,
        module: "noback",
        moduleTitle: "No Back",
        category: WarningCategory.Core,
        message: "",
        coreVersion: "0.7.5",
        urlFoundryHub: "",
        moduleSuggested: [],
        moduleSuggestedTitle: [],
        moduleSuggestedUrl: [],
        moduleSuggestedManifestJson: [],
        moduleSuggestedState: []
    },
    {
        id: 6,
        module: "token-owner-selection-tweak",
        moduleTitle: "Token Owner Selection Tweak",
        category: WarningCategory.Core,
        message: "",
        coreVersion: "0.7.1",
        urlFoundryHub: "",
        moduleSuggested: [],
        moduleSuggestedTitle: [],
        moduleSuggestedUrl: [],
        moduleSuggestedManifestJson: [],
        moduleSuggestedState: []
    },
    {
        id: 7,
        module: "returntosetup",
        moduleTitle: "Return to setup",
        category: WarningCategory.Core,
        message: "",
        coreVersion: "0.7.4",
        urlFoundryHub: "",
        moduleSuggested: [],
        moduleSuggestedTitle: [],
        moduleSuggestedUrl: [],
        moduleSuggestedManifestJson: [],
        moduleSuggestedState: []
    },
    {
        id: 8,
        module: "token-drag-visibility",
        moduleTitle: "Token Drah Visibility",
        category: WarningCategory.Core,
        message: "",
        coreVersion: "0.7.5",
        urlFoundryHub: "",
        moduleSuggested: [],
        moduleSuggestedTitle: [],
        moduleSuggestedUrl: [],
        moduleSuggestedManifestJson: [],
        moduleSuggestedState: []
    },   

    //Broken Warnings (200-299)
    {
        id: 200,
        module: "chat-autoloader",
        moduleTitle: "Chat Autoloader",
        category: WarningCategory.Broken,
        message: "",
        coreVersion: "0.6.6",
        urlFoundryHub: "",
        moduleSuggested: [],
        moduleSuggestedTitle: [],
        moduleSuggestedUrl: [],
        moduleSuggestedManifestJson: [],
        moduleSuggestedState: []
    },
    {
        id: 201,
        module: "chat-colors-and-more",
        moduleTitle: "Chat colors and more",
        category: WarningCategory.Broken,
        message: "",
        coreVersion: "0.6.6",
        urlFoundryHub: "",
        moduleSuggested: [],
        moduleSuggestedTitle: [],
        moduleSuggestedUrl: [],
        moduleSuggestedManifestJson: [],
        moduleSuggestedState: []
    },
    {
        id: 202,
        module: "critical-fumble",
        moduleTitle: "Critical Fumble",
        category: WarningCategory.Broken,
        message: "",
        coreVersion: "0.6.6",
        urlFoundryHub: "",
        moduleSuggested: [],
        moduleSuggestedTitle: [],
        moduleSuggestedUrl: [],
        moduleSuggestedManifestJson: [],
        moduleSuggestedState: []
    },
    {
        id: 203,
        module: "foundry-patrol",
        moduleTitle: "Foundry Patrol",
        category: WarningCategory.Broken,
        message: "",
        coreVersion: "0.7.5",
        urlFoundryHub: "",
        moduleSuggested: [],
        moduleSuggestedTitle: [],
        moduleSuggestedUrl: [],
        moduleSuggestedManifestJson: [],
        moduleSuggestedState: []
    },
    {
        id: 204,
        module: "route-finder",
        moduleTitle: "Route FInder",
        category: WarningCategory.Broken,
        message: "",
        coreVersion: "0.7.5",
        urlFoundryHub: "",
        moduleSuggested: [],
        moduleSuggestedTitle: [],
        moduleSuggestedUrl: [],
        moduleSuggestedManifestJson: [],
        moduleSuggestedState: []
    },
    {
        id: 205,
        module: "bullseye",
        moduleTitle: "Bullseye",
        category: WarningCategory.Broken,
        message: "",
        coreVersion: "0.7.9",
        urlFoundryHub: "",
        moduleSuggested: ["target-enhancements"],
        moduleSuggestedTitle: ["Target Enhancements fork by p4535992"],
        moduleSuggestedUrl: ["https://github.com/p4535992/target-enhancements"],
        moduleSuggestedManifestJson: ["https://raw.githubusercontent.com/p4535992/target-enhancements/master/src/module.json"],
        moduleSuggestedState: [ModuleStateCategory.DEVELOPING]
    },
    {
        id: 206,
        module: "mindmap",
        moduleTitle: "Mindmap",
        category: WarningCategory.Broken,
        message: "",
        coreVersion: "0.7.5",
        urlFoundryHub: "",
        moduleSuggested: ["foundryvtt-mindmap"],
        moduleSuggestedTitle: ["M.I.N.D.M.A.P."],
        moduleSuggestedUrl: ["https://github.com/p4535992/foundryvtt-mindmap"],
        moduleSuggestedManifestJson: ["https://raw.githubusercontent.com/p4535992/foundryvtt-mindmap/master/src/module.json"],
        moduleSuggestedState: [ModuleStateCategory.DEVELOPING]
    },
    {
        id: 207,
        module: "conditions5e",
        moduleTitle: "Conditions 5e",
        category: WarningCategory.Broken,
        message: "",
        coreVersion: "0.7.5",
        urlFoundryHub: "",
        moduleSuggested: ["combat-utility-belt"],
        moduleSuggestedTitle: ["Combat Utility Belt"],
        moduleSuggestedUrl: ["https://github.com/death-save/combat-utility-belt"],
        moduleSuggestedManifestJson: ["https://raw.githubusercontent.com/death-save/combat-utility-belt/master/module.json"],
        moduleSuggestedState: [ModuleStateCategory.STABLE]
    },

    //Replaced Warnings (300-499)
    {
        id: 300,
        module: "dynamiceffects",
        moduleTitle: "Dynamic effects",
        category: WarningCategory.Replaced,
        message: "",
        coreVersion: "0.7.0",
        urlFoundryHub: "",
        moduleSuggested: ["dae"],
        moduleSuggestedTitle: ["Dynamic Active Effects"],
        moduleSuggestedUrl: ["https://gitlab.com/tposney/dae"],
        moduleSuggestedManifestJson: ["https://gitlab.com/tposney/dae/-/raw/master/src/module.json"],
        moduleSuggestedState: [ModuleStateCategory.STABLE]
    },
    {
        id: 301,
        module: "teleport",
        moduleTitle: "Teleport",
        category: WarningCategory.Replaced,
        message: "",
        coreVersion: "0.7.0",
        urlFoundryHub: "",
        moduleSuggested: ["foundryvtt-multilevel-tokens"],
        moduleSuggestedTitle: ["Multilevel Tokens"],
        moduleSuggestedUrl: ["https://github.com/grandseiken/foundryvtt-multilevel-tokens"],
        moduleSuggestedManifestJson: ["https://raw.githubusercontent.com/grandseiken/foundryvtt-multilevel-tokens/master/module.json"],
        moduleSuggestedState: [ModuleStateCategory.STABLE]
    },
    {
        id: 302,
        module: "DancingLights",
        moduleTitle: "Dancing Lights",
        category: WarningCategory.Replaced,
        message: "Now that Foundry has built in light animations, {} is no longer needed and should be uninstalled. For additional animations, install <b><u>CommunityLighting by Blitz</u></b>.",
        coreVersion: "0.7.5",
        urlFoundryHub: "",
        moduleSuggested: ["CommunityLighting"],
        moduleSuggestedTitle: ["Community Lighting by Blitz"],
        moduleSuggestedUrl: ["https://github.com/BlitzKraig/fvtt-CommunityLighting"],
        moduleSuggestedManifestJson: ["https://raw.githubusercontent.com/BlitzKraig/fvtt-CommunityLighting/master/module.json"],
        moduleSuggestedState: [ModuleStateCategory.STABLE]
    },
    {
        id: 303,
        module: "darker-vision-for-5e",
        moduleTitle: "Darker vision for 5e",
        category: WarningCategory.Replaced,
        message: "",
        coreVersion: "0.7.5",
        urlFoundryHub: "",
        moduleSuggested: ["perfect-vision"],
        moduleSuggestedTitle: ["Perfect Vision"],
        moduleSuggestedUrl: ["https://github.com/dev7355608/perfect-vision"],
        moduleSuggestedManifestJson: ["https://raw.githubusercontent.com/dev7355608/perfect-vision/main/module.json"],
        moduleSuggestedState: [ModuleStateCategory.STABLE]
    },
    {
        id: 304,
        module: "darkvision5e",
        moduleTitle: "Darkvision 5e",
        category: WarningCategory.Replaced,
        message: "",
        coreVersion: "0.7.5",
        urlFoundryHub: "",
        moduleSuggested: ["perfect-vision"],
        moduleSuggestedTitle: ["Perfect Vision"],
        moduleSuggestedUrl: ["https://github.com/dev7355608/perfect-vision"],
        moduleSuggestedManifestJson: ["https://raw.githubusercontent.com/dev7355608/perfect-vision/main/module.json"],
        moduleSuggestedState: [ModuleStateCategory.STABLE]
    },
    {
        id: 305,
        module: "minor-qol",
        moduleTitle: "Minor Quality of Life Improvements",
        category: WarningCategory.Replaced,
        message: "",
        coreVersion: "0.7.5",
        urlFoundryHub: "",
        moduleSuggested: ["midi-qol"],
        moduleSuggestedTitle: ["Midi Quality of Life Improvements"],
        moduleSuggestedUrl: ["https://gitlab.com/tposney/midi-qol"],
        moduleSuggestedManifestJson: ["https://gitlab.com/tposney/midi-qol/-/raw/master/src/module.json"],
        moduleSuggestedState: [ModuleStateCategory.STABLE]
    },
    {
        id: 306,
        module: "gm-bg",
        moduleTitle: "GM Background",
        category: WarningCategory.Replaced,
        message: "",
        coreVersion: "0.7.5",
        urlFoundryHub: "",
        moduleSuggested: ["scenery"],
        moduleSuggestedTitle: ["Scenery"],
        moduleSuggestedUrl: ["https://github.com/VanceCole/scenery"],
        moduleSuggestedManifestJson: ["https://raw.githubusercontent.com/VanceCole/scenery/master/module.json"],
        moduleSuggestedState: [ModuleStateCategory.STABLE]
    },
    {
        id: 307,
        module: "cursor-zoom",
        moduleTitle: "Cursor Zoom",
        category: WarningCategory.Replaced,
        message: "",
        coreVersion: "0.6.0",
        urlFoundryHub: "",
        moduleSuggested: ["zoom-pan-options"],
        moduleSuggestedTitle: ["Zoom/Pan Options"],
        moduleSuggestedUrl: ["https://github.com/itamarcu/ZoomPanOptions"],
        moduleSuggestedManifestJson: ["https://raw.githubusercontent.com/itamarcu/ZoomPanOptions/master/module.json"],
        moduleSuggestedState: [ModuleStateCategory.STABLE]
    },
    {
        id: 308,
        module: "vtta-dndbeyond",
        moduleTitle: "VTTA DnD Beyond",
        category: WarningCategory.Replaced,
        message: "D&D Beyond Importer",
        coreVersion: "0.6.0",
        urlFoundryHub: "",
        moduleSuggested: ["ddb-importer"],
        moduleSuggestedTitle: ["D&D Beyond Importer by mr Primate"],
        moduleSuggestedUrl: ["https://github.com/MrPrimate/ddb-importer"],
        moduleSuggestedManifestJson: ["https://raw.githubusercontent.com/MrPrimate/ddb-importer/master/module.json"],
        moduleSuggestedState: [ModuleStateCategory.STABLE]
    },
    {
        id: 309,
        module: "ddb-importer",
        moduleTitle: "DDB Importer",
        category: WarningCategory.Replaced,
        message: "D&D Beyond Importer (by MrPrimate)",
        coreVersion: "0.6.0",
        highestVersion: "0.1.9",
        inactive: true,
        urlFoundryHub: "",
        moduleSuggested: ["ddb-importer"],
        moduleSuggestedTitle: ["D&D Beyond Importer by mr Primate"],
        moduleSuggestedUrl: ["https://github.com/MrPrimate/ddb-importer"],
        moduleSuggestedManifestJson: ["https://raw.githubusercontent.com/MrPrimate/ddb-importer/master/module.json"],
        moduleSuggestedState: [ModuleStateCategory.STABLE]
    },
    {
        id: 310,
        module: "fvtt-party",
        moduleTitle: "FVTT Party",
        category: WarningCategory.Replaced,
        message: "Party Overview" + " It's a different module, despite the same name.",
        coreVersion: "0.6.0",
        urlFoundryHub: "",
        moduleSuggested: ["party-overview", "illandril-token-tooltips", "token-tooltip-alt"],
        moduleSuggestedTitle: ["Party Overview by LoFD", "Illandril's Token Tooltip", "Token Tooltip Alt"],
        moduleSuggestedUrl: ["https://github.com/League-of-Foundry-Developers/party-overview", "https://github.com/illandril/FoundryVTT-token-tooltips", "https://github.com/bmarian/token-tooltip-alt"],
        moduleSuggestedManifestJson: ["https://raw.githubusercontent.com/League-of-Foundry-Developers/party-overview/master/module.json","https://raw.githubusercontent.com/illandril/FoundryVTT-token-tooltips/master/module/module.json", "https://raw.githubusercontent.com/bmarian/token-tooltip-alt/master/module.json"],
        moduleSuggestedState: [ModuleStateCategory.STABLE, ModuleStateCategory.STABLE, ModuleStateCategory.STABLE]
    },
    {
        id: 311,
        module: "vtta-party",
        moduleTitle: "VTTA Party",
        category: WarningCategory.Replaced,
        message: `<b><u>Virtual Tabletop Assets - Party Overview</u></b> is no longer being maintained and could break with any Foundry update.<br>
        <p>For a module that has has a similar Party Overview functionality, try <b><u>Party Overview</u></b>.</p>
        For a module that lets you create token tooltips, try <b><u>Illandril's Token Tooltips</u></b> or <b><u>Token Tooltip Alt</u></b>`,
        coreVersion: "0.7.5",
        urlFoundryHub: "",
        moduleSuggested: ["party-overview", "illandril-token-tooltips", "token-tooltip-alt"],
        moduleSuggestedTitle: ["Party Overview by LoFD", "Illandril's Token Tooltip", "Token Tooltip Alt"],
        moduleSuggestedUrl: ["https://github.com/League-of-Foundry-Developers/party-overview", "https://github.com/illandril/FoundryVTT-token-tooltips", "https://github.com/bmarian/token-tooltip-alt"],
        moduleSuggestedManifestJson: ["https://raw.githubusercontent.com/League-of-Foundry-Developers/party-overview/master/module.json","https://raw.githubusercontent.com/illandril/FoundryVTT-token-tooltips/master/module/module.json", "https://raw.githubusercontent.com/bmarian/token-tooltip-alt/master/module.json"],
        moduleSuggestedState: [ModuleStateCategory.STABLE, ModuleStateCategory.STABLE, ModuleStateCategory.STABLE]
    },
    {
        id: 312,
        module: "roll20npcimporter",
        moduleTitle: "Roll20 Npc Importer",
        category: WarningCategory.Replaced,
        message: "R20 Converter" + " It is available via Kakaroto's Patreon.",
        coreVersion: "0.6.6",
        urlFoundryHub: "",
        moduleSuggested: [],
        moduleSuggestedTitle: [],
        moduleSuggestedUrl: [],
        moduleSuggestedManifestJson: [],
        moduleSuggestedState: []
    },
    {
        id: 313,
        module: "mess",
        moduleTitle: "M.E.S.S",
        category: WarningCategory.Replaced,
        message: `<p>For a module that handles rolls in the same way, try <b><u>Mars 5e</u></b>.</p>
        For a module that enhances templates, including video templates, try <b><u>Token Magic FX</u></b>`,
        coreVersion: "0.7.5",
        moduleSuggested: ["mars-5e"],
        moduleSuggestedTitle: ["MARS 5e - Moerills alternative rolling style for 5e"],
        moduleSuggestedUrl: ["https://github.com/Moerill/fvtt-mars-5e"],
        moduleSuggestedManifestJson: ["https://raw.githubusercontent.com/Moerill/fvtt-mars-5e/master/module.json"],
        moduleSuggestedState: [ModuleStateCategory.STABLE]
    },
    {
        id: 314,
        module: "canvas-scroll",
        moduleTitle: "Canvas Scroll",
        category: WarningCategory.Replaced,
        message: "",
        coreVersion: "0.7.5",
        moduleSuggested: ["zoom-pan-options"],
        moduleSuggestedTitle: ["Zoom/Pan Options"],
        moduleSuggestedUrl: ["https://github.com/itamarcu/ZoomPanOptions"],
        moduleSuggestedManifestJson: ["https://raw.githubusercontent.com/itamarcu/ZoomPanOptions/master/module.json"],
        moduleSuggestedState: [ModuleStateCategory.STABLE]
    },
    {
        id: 315,
        module: "token-action-animations",
        moduleTitle: "Token Action Animations",
        category: WarningCategory.Replaced,
        message: "",
        coreVersion: "0.7.5",
        moduleSuggested: ["automated-jb2a-animations"],
        moduleSuggestedTitle: ["Automated Animations DnD5e"],
        moduleSuggestedUrl: ["https://github.com/otigon/automated-jb2a-animations"],
        moduleSuggestedManifestJson: ["https://raw.githubusercontent.com/otigon/automated-jb2a-animations/main/module.json"],
        moduleSuggestedState: [ModuleStateCategory.STABLE]
    },
    {
        id: 316,
        module: "AdvancedLightingToolkit",
        moduleTitle: "Advanced Lighting Toolkit",
        category: WarningCategory.Replaced,
        message: "",
        coreVersion: "0.7.5",
        moduleSuggested: ["CommunityLighting"],
        moduleSuggestedTitle: ["Community Lighting by Blitz"],
        moduleSuggestedUrl: ["https://github.com/BlitzKraig/fvtt-CommunityLighting"],
        moduleSuggestedManifestJson: ["https://raw.githubusercontent.com/BlitzKraig/fvtt-CommunityLighting/master/module.json"],
        moduleSuggestedState: [ModuleStateCategory.STABLE]
    },
    {
        id: 317,
        module: "combatready",
        moduleTitle: "Combat Ready",
        category: WarningCategory.Replaced,
        message: "",
        coreVersion: "0.7.9",
        urlFoundryHub: "https://www.foundryvtt-hub.com/package/combatready",
        moduleSuggested: ["monks-little-details"],
        moduleSuggestedTitle: ["Monk's Little Details"],
        moduleSuggestedUrl: ["https://github.com/ironmonk88/monks-little-details"],
        moduleSuggestedManifestJson: ["https://raw.githubusercontent.com/Moerill/fvtt-pointer/master/module.json"],
        moduleSuggestedState: [ModuleStateCategory.STABLE]
    },
    {
      id: 318,
      module: "pings",
      moduleTitle: "Pings",
      category: WarningCategory.Replaced,
      message: "PnP - Pointer and Pings!",
      coreVersion: "0.7.9",
      moduleSuggested: ["pointer"],
      moduleSuggestedTitle: ["PnP - Pointer and Pings!"],
      moduleSuggestedUrl: ["https://github.com/Moerill/fvtt-pointer"],
      moduleSuggestedManifestJson: ["https://raw.githubusercontent.com/Moerill/fvtt-pointer/master/module.json"],
      moduleSuggestedState: [ModuleStateCategory.STABLE]
    },
    {
        id: 319,
        module: "target-enhancements",
        moduleTitle: "Target Enhancements",
        category: WarningCategory.Replaced,
        message: "",
        coreVersion: "0.7.9",
        moduleUrl: "https://github.com/eadorin/target-enhancements",
        moduleSuggested: ["target-enhancements"],
        moduleSuggestedTitle: ["Target Enhancements fork by p4535992"],
        moduleSuggestedUrl: ["https://github.com/p4535992/target-enhancements"],
        moduleSuggestedManifestJson: ["https://raw.githubusercontent.com/p4535992/target-enhancements/master/src/module.json"],
        moduleSuggestedState: [ModuleStateCategory.DEVELOPING]
    },
    {
        id: 320,
        module: "ShowDragDistance",
        moduleTitle: "Show Drag DIstance",
        category: WarningCategory.Replaced,
        message: "",
        coreVersion: "0.7.9",
        moduleUrl: "https://github.com/wsaunders1014/ShowDragDistance",
        moduleSuggested: ["drag-ruler"],
        moduleSuggestedTitle: ["Drag Ruler"],
        moduleSuggestedUrl: ["https://github.com/manuelVo/foundryvtt-drag-ruler"],
        moduleSuggestedManifestJson: ["https://raw.githubusercontent.com/manuelVo/foundryvtt-drag-ruler/develop/module.json"],
        moduleSuggestedState: [ModuleStateCategory.STABLE]
    },
    {
        id: 321,
        module: "chatdamagebuttons5e",
        moduleTitle: "Chat Damage Button 5e",
        category: WarningCategory.Replaced,
        message: "",
        coreVersion: "0.4.5",
        moduleSuggested: ["midi-qol"],
        moduleSuggestedTitle: ["Midi Quality of Life Improvements"],
        moduleSuggestedUrl: ["https://gitlab.com/tposney/midi-qol"],
        moduleSuggestedManifestJson: ["https://gitlab.com/tposney/midi-qol/-/raw/master/src/module.json"],
        moduleSuggestedState: [ModuleStateCategory.STABLE]
    },
    {
        id: 322,
        module: "music-assist",
        moduleTitle: "Music Assist",
        category: WarningCategory.Replaced,
        message: "",
        coreVersion: "0.5.5",
        moduleSuggested: ["bellows"],
        moduleSuggestedTitle: ["Bellows"],
        moduleSuggestedUrl: ["https://github.com/casualchameleon/Bellows"],
        moduleSuggestedManifestJson: ["https://raw.githubusercontent.com/casualchameleon/Bellows/master/module.json"],
        moduleSuggestedState: [ModuleStateCategory.STABLE]
    },
    {
        id: 323,
        module: "pushTokenBack",
        moduleTitle: "Push Tokens Back",
        category: WarningCategory.Replaced,
        message: "",
        coreVersion: "0.7.9",
        moduleSuggested: ["TokensVisible"],
        moduleSuggestedTitle: ["Your Tokens Visible"],
        moduleSuggestedUrl: ["https://github.com/David-Zvekic/TokensVisible"],
        moduleSuggestedManifestJson: ["https://raw.githubusercontent.com/David-Zvekic/TokensVisible/main/module.json"],
        moduleSuggestedState: [ModuleStateCategory.STABLE]
    },
    {
        id: 324,
        module: "fvtt-cycle-token-stack",
        moduleTitle: "Cycle Token Stack",
        category: WarningCategory.Replaced,
        message: "",
        coreVersion: "0.7.9",
        moduleSuggested: ["TokensVisible"],
        moduleSuggestedTitle: ["Your Tokens Visible"],
        moduleSuggestedUrl: ["https://github.com/David-Zvekic/TokensVisible"],
        moduleSuggestedManifestJson: ["https://raw.githubusercontent.com/David-Zvekic/TokensVisible/main/module.json"],
        moduleSuggestedState: [ModuleStateCategory.STABLE]
    },
    {
        id: 325,
        module: "zsync",
        moduleTitle: "zsync",
        category: WarningCategory.Replaced,
        message: "",
        coreVersion: "0.7.9",
        moduleSuggested: ["TokensVisible"],
        moduleSuggestedTitle: ["Your Tokens Visible"],
        moduleSuggestedUrl: ["https://github.com/David-Zvekic/TokensVisible"],
        moduleSuggestedManifestJson: ["https://raw.githubusercontent.com/David-Zvekic/TokensVisible/main/module.json"],
        moduleSuggestedState: [ModuleStateCategory.STABLE]
    },
    {
        id: 326,
        module: "everybody-look",
        moduleTitle: "Everybody Look",
        category: WarningCategory.Replaced,
        message: "",
        coreVersion: "0.7.9",
        moduleUrl: "https://github.com/winks-vtt/everybody-look",
        moduleSuggested: ["pull-players-to-scene"],
        moduleSuggestedTitle: ["Pull Players to Scene"],
        moduleSuggestedUrl: ["https://github.com/Mr-Byte/pull-players-to-scene"],
        moduleSuggestedManifestJson: ["https://raw.githubusercontent.com/Mr-Byte/pull-players-to-scene/main/module.json"],
        moduleSuggestedState: [ModuleStateCategory.STABLE]
    },
    {
        id: 327,
        module: "adjusted-movement",
        moduleTitle: "Adjusted Movement",
        category: WarningCategory.Replaced,
        message: "",
        coreVersion: "0.7.7",
        moduleUrl: "https://github.com/eadorin/adjusted-movement",
        moduleSuggested: ["NotYourTurn"],
        moduleSuggestedTitle: ["Not Your Turn!"],
        moduleSuggestedUrl: ["https://github.com/CDeenen/NotYourTurn"],
        moduleSuggestedManifestJson: ["https://raw.githubusercontent.com/CDeenen/NotYourTurn/master/module.json"],
        moduleSuggestedState: [ModuleStateCategory.STABLE]
    },
    {
        id: 328,
        module: "lets-trade-5e",
        moduleTitle: "Lets Trade 5e",
        category: WarningCategory.Replaced,
        message: "",
        coreVersion: "0.7.9",
        moduleUrl: "https://github.com/KageJittai/lets-trade-5e",
        moduleSuggested: ["give-item"],
        moduleSuggestedTitle: ["FoundryVTT-GiveItem"],
        moduleSuggestedUrl: ["https://github.com/Sepichat/FoundryVTT-GiveItem"],
        moduleSuggestedManifestJson: ["https://raw.githubusercontent.com/Sepichat/FoundryVTT-GiveItem/main/module.json"],
        moduleSuggestedState: [ModuleStateCategory.STABLE]
    },
    {
        id: 329,
        module: "searchanywhere",
        moduleTitle: "Search Anywhere",
        category: WarningCategory.Replaced,
        message: "",
        coreVersion: "0.7.9",
        moduleUrl: "https://gitlab.com/riccisi/foundryvtt-search-anywhere",
        moduleSuggested: ["quick-insert"],
        moduleSuggestedTitle: ["Quick Insert"],
        moduleSuggestedUrl: ["https://gitlab.com/fvtt-modules-lab/quick-insert"],
        moduleSuggestedManifestJson: ["https://gitlab.com/fvtt-modules-lab/quick-insert/-/raw/master/src/module.json"],
        moduleSuggestedState: [ModuleStateCategory.STABLE]
    },
    {
        id: 330,
        module: "token-health",
        moduleTitle: "Token Health",
        category: WarningCategory.Replaced,
        message: "",
        coreVersion: "0.7.3",
        moduleUrl: "https://github.com/tonifisler/foundry-token-health",
        moduleSuggested: ["midi-qol"],
        moduleSuggestedTitle: ["Midi Quality of Life Improvements"],
        moduleSuggestedUrl: ["https://gitlab.com/tposney/midi-qol"],
        moduleSuggestedManifestJson: ["https://gitlab.com/tposney/midi-qol/-/raw/master/src/module.json"],
        moduleSuggestedState: [ModuleStateCategory.STABLE]
    },
    //Delisted Warnings (500-699)
    {
        id: 500,
        module: "fog-tools",
        moduleTitle: "Fog Tools",
        category: WarningCategory.Delisted,
        message: "",
        coreVersion: "0.8.0",
        moduleUrl: "https://github.com/VanceCole/fog-tools",
        urlFoundryHub: "",
        moduleSuggested: [],
        moduleSuggestedTitle: [],
        moduleSuggestedUrl: [],
        moduleSuggestedManifestJson: [],
        moduleSuggestedState: []
    },
    {
        id: 501,
        module: "self-token-delete",
        moduleTitle: "Self Token Delete",
        category: WarningCategory.Delisted,
        message: "",
        coreVersion: "0.7.5",
        moduleUrl: "https://github.com/Corvimae/fvtt-self-token-delete",
        urlFoundryHub: "",
        moduleSuggested: [],
        moduleSuggestedTitle: [],
        moduleSuggestedUrl: [],
        moduleSuggestedManifestJson: [],
        moduleSuggestedState: []
    },
    {
        id: 502,
        module: "vtta-iconizer",
        moduleTitle: "VTTA Iconizer",
        category: WarningCategory.Delisted,
        message: "",
        coreVersion: "0.8.0",
        moduleUrl: "https://github.com/VTTAssets/vtta-iconizer",
        urlFoundryHub: "",
        moduleSuggested: ["vtta-iconizer"],
        moduleSuggestedTitle: ["VTTA Iconizer (by MrPrimate)"],
        moduleSuggestedUrl: ["https://github.com/MrPrimate/vtta-iconizer"],
        moduleSuggestedManifestJson: ["https://raw.githubusercontent.com/MrPrimate/vtta-iconizer/master/module.json"],
        moduleSuggestedState: [ModuleStateCategory.MAINTENANCE]
    },
    {
        id: 503,
        module: "vtta-didyouknow",
        moduleTitle: "VTTA Did you Know",
        category: WarningCategory.Delisted,
        message: "",
        coreVersion: "0.8.0",
        moduleUrl: "https://github.com/VTTAssets/vtta-didyouknow",
        urlFoundryHub: "https://www.foundryvtt-hub.com/package/vtta-didyouknow",
        moduleSuggested: [],
        moduleSuggestedTitle: [],
        moduleSuggestedUrl: [],
        moduleSuggestedManifestJson: [],
        moduleSuggestedState: []
    },
    {
        id: 504,
        module: "streaming-mode",
        moduleTitle: "Streaming Mode",
        category: WarningCategory.Delisted,
        message: "",
        coreVersion: "0.8.0",
        moduleUrl: "https://github.com/cswendrowski/FoundryVTT-Streaming-Mode",
        urlFoundryHub: "",
        moduleSuggested: [],
        moduleSuggestedTitle: [],
        moduleSuggestedUrl: [],
        moduleSuggestedManifestJson: [],
        moduleSuggestedState: []
    },
    {
        id: 505,
        module: "cursor-hider",
        moduleTitle: "Cursor Hider",
        category: WarningCategory.Delisted,
        message: "",
        coreVersion: "0.8.0",
        moduleUrl: "https://gitlab.com/foundry-azzurite/cursor-hider",
        urlFoundryHub: "https://www.foundryvtt-hub.com/package/cursor-hider",
        moduleSuggested: [],
        moduleSuggestedTitle: [],
        moduleSuggestedUrl: [],
        moduleSuggestedManifestJson: [],
        moduleSuggestedState: []
    },
    {
        id: 506,
        module: "foundryvtt-lingering-injuries",
        moduleTitle: "FoundryVTT Lingering Injuries",
        category: WarningCategory.Delisted,
        message: "",
        coreVersion: "0.7.1",
        moduleUrl: "https://gitlab.com/p4535992/foundryvtt-lingering-injuries",
        urlFoundryHub: "",
        moduleSuggested: [],
        moduleSuggestedTitle: [],
        moduleSuggestedUrl: [],
        moduleSuggestedManifestJson: [],
        moduleSuggestedState: []
    },
    //Abbandoned Warnings (600-799)
    {
        id: 600,
        module: "gm-notes",
        moduleTitle: "GM Notes",
        category: WarningCategory.Abbandoned,
        message: "",
        coreVersion: "0.7.5",
        moduleUrl: "https://github.com/syl3r86/gm-notes",
        urlFoundryHub: "",
        moduleSuggested: [],
        moduleSuggestedTitle: [],
        moduleSuggestedUrl: [],
        moduleSuggestedManifestJson: [],
        moduleSuggestedState: []
    },
    {
        id: 601,
        module: "gm-secrets",
        moduleTitle: "GM Secret",
        category: WarningCategory.Abbandoned,
        message: "",
        coreVersion: "0.7.9",
        moduleUrl: "https://github.com/schultzcole/FVTT-GM-Secret-Block",
        urlFoundryHub: "", 
        moduleSuggested: [],
        moduleSuggestedTitle: [],
        moduleSuggestedUrl: [],
        moduleSuggestedManifestJson: [],
        moduleSuggestedState: []
    },
    {
        id: 602,
        module: "turnAlert",
        moduleTitle: "FVTT Turn Alert",
        category: WarningCategory.Abbandoned,
        message: "",
        coreVersion: "0.7.9",
        moduleUrl: "https://github.com/schultzcole/FVTT-Turn-Alert",
        urlFoundryHub: "", 
        moduleSuggested: [],
        moduleSuggestedTitle: [],
        moduleSuggestedUrl: [],
        moduleSuggestedManifestJson: [],
        moduleSuggestedState: []
    },
    {
        id: 603,
        module: "token-auras",
        moduleTitle: "Token Aura",
        category: WarningCategory.Abbandoned,
        message: "",
        coreVersion: "0.7.7",
        moduleUrl: "https://bitbucket.org/Fyorl/token-auras",
        urlFoundryHub: "", 
        moduleSuggested: ["foundryvtt-tokeneffects"],
        moduleSuggestedTitle: ["Token Effects"],
        moduleSuggestedUrl: ["https://github.com/p4535992/foundryvtt-tokeneffects"],
        moduleSuggestedManifestJson: ["https://raw.githubusercontent.com/p4535992/foundryvtt-tokeneffects/master/src/module.json"],
        moduleSuggestedState: [ModuleStateCategory.DEVELOPING]  
    },
    {
        id: 604,
        module: "workshop-party-unit-frames",
        moduleTitle: "Workshop's Party Unit Frames",
        category: WarningCategory.Abbandoned,
        message: "",
        coreVersion: "0.7.0",
        moduleUrl: "https://github.com/Foundry-Workshop/party-unit-frames",
        urlFoundryHub: "", 
        moduleSuggested: [],
        moduleSuggestedTitle: [],
        moduleSuggestedUrl: [],
        moduleSuggestedManifestJson: [],
        moduleSuggestedState: []
    },
    {
        id: 605,
        module: "ambientdoors",
        moduleTitle: "Ambient Doors",
        category: WarningCategory.Abbandoned,
        message: "",
        coreVersion: "0.7.9",
        moduleUrl: "https://github.com/EndlesNights/ambientdoors",
        urlFoundryHub: "", 
        moduleSuggested: [],
        moduleSuggestedTitle: [],
        moduleSuggestedUrl: [],
        moduleSuggestedManifestJson: [],
        moduleSuggestedState: []
    },
    {
        id: 606,
        module: "backgroundless-pins",
        moduleTitle: "FVTT-Backgroundless-Pins",
        category: WarningCategory.Abbandoned,
        message: "",
        coreVersion: "0.7.9",
        moduleUrl: "https://github.com/schultzcole/FVTT-Backgroundless-Pins",
        urlFoundryHub: "", 
        moduleSuggested: [],
        moduleSuggestedTitle: [],
        moduleSuggestedUrl: [],
        moduleSuggestedManifestJson: [],
        moduleSuggestedState: []
    },
    {
        id: 607,
        module: "selectiveshow",
        moduleTitle: "FVTT-SelectiveShow",
        category: WarningCategory.Abbandoned,
        message: "",
        coreVersion: "0.7.9",
        moduleUrl: "https://github.com/moo-man/FVTT-SelectiveShow",
        urlFoundryHub: "", 
        moduleSuggested: [],
        moduleSuggestedTitle: [],
        moduleSuggestedUrl: [],
        moduleSuggestedManifestJson: [],
        moduleSuggestedState: []
    },
    {
        id: 608,
        module: "token-animation-tools",
        moduleTitle: "FVTT Token Animation Tools",
        category: WarningCategory.Abbandoned,
        message: "",
        coreVersion: "0.7.9",
        moduleUrl: "https://github.com/ruipin/fvtt-token-animation-tools",
        urlFoundryHub: "", 
        moduleSuggested: [],
        moduleSuggestedTitle: [],
        moduleSuggestedUrl: [],
        moduleSuggestedManifestJson: [],
        moduleSuggestedState: []
    },
    {
        id: 609,
        module: "FoundryPLANT",
        moduleTitle: "Foundry PLANT (PLAyer Needs Tracker)",
        category: WarningCategory.Abbandoned,
        message: "",
        coreVersion: "0.7.7",
        moduleUrl: "https://github.com/GameMaker/FoundryPLANT",
        urlFoundryHub: "", 
        moduleSuggested: [],
        moduleSuggestedTitle: [],
        moduleSuggestedUrl: [],
        moduleSuggestedManifestJson: [],
        moduleSuggestedState: []
    }
]
